### ISSUE TITLE
Release master branch to pypi

### ISSUE THREAD

**Issue by 1oglop1** [BuzonIO/zipfly#81]
It looks like the last version on PyPI has been published 2 years ago and there have been many changes in the code since.

It would be helpful if you could release the latest changes.

PS since the project is already using GH action for testing, it may be helpful to set up GH actions for release as well.

https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

https://github.com/marketplace/actions/pypi-publish

**Comment by sandes** [comment]
Thank you for your message!
